// <auto-generated />
using System;
using ApiLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240523120303_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiLibrary.Models.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Benefits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food and drinks"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Recreation"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Culture"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Travelling"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Shopping"
                        });
                });

            modelBuilder.Entity("ApiLibrary.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 10000m,
                            CardNumber = "1234123412341234",
                            EmployeeId = 1,
                            Pin = "$2a$11$7s.P.jf4AsCbImtAc6PHrOAvy7CY5utD1CdBZhL7v1U0xtRP39F5K"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 20000m,
                            CardNumber = "2345234523452345",
                            EmployeeId = 2,
                            Pin = "$2a$11$3Z6eXNHC09ZH80Mc1ylXu.zT9spjQ7BDc2G9crnEd1VpL6uZU4.DO"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 30000m,
                            CardNumber = "3456345634563456",
                            EmployeeId = 3,
                            Pin = "$2a$11$84GPa/OEi3GuXhWzKw6axOKva7ThCizKiZw3vNdjNoU/ebXwcSzXO"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 40000m,
                            CardNumber = "4567456745674567",
                            EmployeeId = 4,
                            Pin = "$2a$11$zmN4bmKUI8QR84vXmNx/tOWmn8DnLdxs9ie9qV51YB3U4ZcIj3cEq"
                        },
                        new
                        {
                            Id = 5,
                            Balance = 50000m,
                            CardNumber = "5678567856785678",
                            EmployeeId = 5,
                            Pin = "$2a$11$WV9/qGn2IJNMUM3uNrkSAeUH4aTO0/GMH0YLG17/yBuXOaNZqRlHi"
                        },
                        new
                        {
                            Id = 6,
                            Balance = 60000m,
                            CardNumber = "6789678967896789",
                            EmployeeId = 6,
                            Pin = "$2a$11$6Q67R1MhYdKxNVaVxGbOo.tQtDRY21lRqObIEaK1f1hM8a2lxgKQy"
                        },
                        new
                        {
                            Id = 7,
                            Balance = 70000m,
                            CardNumber = "7890789078907890",
                            EmployeeId = 7,
                            Pin = "$2a$11$EwlgBWHdRv/g5ZlSDdTQTugIvoISV7X7DvHngWtOoaYCIRp1VluKO"
                        },
                        new
                        {
                            Id = 8,
                            Balance = 80000m,
                            CardNumber = "8901890189018901",
                            EmployeeId = 8,
                            Pin = "$2a$11$FsXXBCReE7r05zRZEJ42oexX0HqfyxSOAuxWhR7JCX9gAgCrsJPHm"
                        },
                        new
                        {
                            Id = 9,
                            Balance = 90000m,
                            CardNumber = "9012901290129012",
                            EmployeeId = 9,
                            Pin = "$2a$11$HMu9QpU4bEwX5.U.Ij460O4KNbcAIUmnYi86/WenceNFIRABSVroW"
                        });
                });

            modelBuilder.Entity("ApiLibrary.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Standard Users"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Premium Users"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Platinum Users"
                        });
                });

            modelBuilder.Entity("ApiLibrary.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 23, 14, 2, 56, 74, DateTimeKind.Local).AddTicks(1463),
                            Email = "admin@benefitseller.com",
                            IsDeleted = false,
                            Name = "BenefitSeller",
                            Password = "$2a$11$8sFXIRFZJS4qO3MikehIr.eVq0cEEFlKkPDsDrlOakVHT9Los.Erq",
                            RefreshToken = "",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 23, 14, 2, 56, 175, DateTimeKind.Local).AddTicks(4786),
                            Email = "info@techcorp.com",
                            IsDeleted = false,
                            Name = "TechCorp",
                            Password = "$2a$11$Tx36TrBxzv1TbGICKQmIq.aMOwzJW9hXO/PRKXWHK8sKkCiyDnNCq",
                            RefreshToken = "",
                            Role = "Company"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 23, 14, 2, 56, 278, DateTimeKind.Local).AddTicks(884),
                            Email = "contact@globalsolutions.com",
                            IsDeleted = false,
                            Name = "GlobalSolutions",
                            Password = "$2a$11$njSXh9sQEnJ4ILz3NjPbROZMCz.cYKT4W9M6pwwM1VQnjG7EwWP1e",
                            RefreshToken = "",
                            Role = "Company"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 23, 14, 2, 56, 380, DateTimeKind.Local).AddTicks(3391),
                            Email = "hello@innovatetech.com",
                            IsDeleted = false,
                            Name = "InnovateTech",
                            Password = "$2a$11$spDfwvDr.w8LMtLrYUhhVuBD35Csai7dwnFmih2XKx34R7FfbYXlm",
                            RefreshToken = "",
                            Role = "Company"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 23, 14, 2, 56, 483, DateTimeKind.Local).AddTicks(4129),
                            Email = "info@swiftenterprises.com",
                            IsDeleted = false,
                            Name = "SwiftEnterprises",
                            Password = "$2a$11$SIvry5jFyc7KyPtqkygVaOym1ZDUMN4HkjZzgBiBkCzvBLlU2jSze",
                            RefreshToken = "",
                            Role = "Company"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 5, 23, 14, 2, 56, 594, DateTimeKind.Local).AddTicks(5023),
                            Email = "contact@alphainnovations.com",
                            IsDeleted = false,
                            Name = "AlphaInnovations",
                            Password = "$2a$11$k3l0BngEYA/20.QaodYK2.qyRh.OtPNIhVjrt0r68Zgg8V4R2.wRC",
                            RefreshToken = "",
                            Role = "Company"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 5, 23, 14, 2, 56, 705, DateTimeKind.Local).AddTicks(8096),
                            Email = "info@globalnetworks.com",
                            IsDeleted = false,
                            Name = "GlobalNetworks",
                            Password = "$2a$11$F2eyoqVbAu3vHkpMWaF2jOjQ3A4Ks9oW/xszRbXuC3y9H/aqEzfxK",
                            RefreshToken = "",
                            Role = "Company"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 5, 23, 14, 2, 56, 816, DateTimeKind.Local).AddTicks(998),
                            Email = "hello@techsavvy.com",
                            IsDeleted = false,
                            Name = "TechSavvy",
                            Password = "$2a$11$8KfH5ZrWTGn.bZzlFsHHqOeRgE9UXH8ejjxBYne029ardJV5RKaq.",
                            RefreshToken = "",
                            Role = "Company"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 5, 23, 14, 2, 56, 926, DateTimeKind.Local).AddTicks(6233),
                            Email = "info@innovatehub.com",
                            IsDeleted = false,
                            Name = "InnovateHub",
                            Password = "$2a$11$NZyWk/dhoetx008s3bgAAepl44wXrA8E6cB5FMp9FVuHw19ufgfJO",
                            RefreshToken = "",
                            Role = "Company"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 5, 23, 14, 2, 57, 38, DateTimeKind.Local).AddTicks(2411),
                            Email = "contact@alphatech.com",
                            IsDeleted = false,
                            Name = "AlphaTech",
                            Password = "$2a$11$0..JsgaAxQOP0Var2RRWJOtWAlHN3EV.8h5Kw/EKLgEW24NSDVTjq",
                            RefreshToken = "",
                            Role = "Company"
                        });
                });

            modelBuilder.Entity("ApiLibrary.Models.CompanyBenefits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BenefitId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyBenefits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BenefitId = 1,
                            CompanyId = 2
                        },
                        new
                        {
                            Id = 2,
                            BenefitId = 3,
                            CompanyId = 2
                        },
                        new
                        {
                            Id = 3,
                            BenefitId = 5,
                            CompanyId = 2
                        },
                        new
                        {
                            Id = 4,
                            BenefitId = 4,
                            CompanyId = 3
                        },
                        new
                        {
                            Id = 5,
                            BenefitId = 3,
                            CompanyId = 3
                        },
                        new
                        {
                            Id = 6,
                            BenefitId = 1,
                            CompanyId = 4
                        },
                        new
                        {
                            Id = 7,
                            BenefitId = 5,
                            CompanyId = 4
                        },
                        new
                        {
                            Id = 8,
                            BenefitId = 6,
                            CompanyId = 4
                        },
                        new
                        {
                            Id = 9,
                            BenefitId = 2,
                            CompanyId = 5
                        },
                        new
                        {
                            Id = 10,
                            BenefitId = 6,
                            CompanyId = 5
                        },
                        new
                        {
                            Id = 11,
                            BenefitId = 4,
                            CompanyId = 6
                        },
                        new
                        {
                            Id = 12,
                            BenefitId = 3,
                            CompanyId = 6
                        },
                        new
                        {
                            Id = 13,
                            BenefitId = 2,
                            CompanyId = 7
                        },
                        new
                        {
                            Id = 14,
                            BenefitId = 1,
                            CompanyId = 7
                        },
                        new
                        {
                            Id = 15,
                            BenefitId = 1,
                            CompanyId = 8
                        },
                        new
                        {
                            Id = 16,
                            BenefitId = 4,
                            CompanyId = 8
                        },
                        new
                        {
                            Id = 17,
                            BenefitId = 3,
                            CompanyId = 9
                        },
                        new
                        {
                            Id = 18,
                            BenefitId = 2,
                            CompanyId = 9
                        },
                        new
                        {
                            Id = 19,
                            BenefitId = 1,
                            CompanyId = 9
                        },
                        new
                        {
                            Id = 20,
                            BenefitId = 3,
                            CompanyId = 10
                        },
                        new
                        {
                            Id = 21,
                            BenefitId = 2,
                            CompanyId = 10
                        });
                });

            modelBuilder.Entity("ApiLibrary.Models.CompanyMerchantsDiscounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("MerchantId");

                    b.ToTable("CompanyMerchantsDiscounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 2,
                            Discount = 10m,
                            MerchantId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            Discount = 15m,
                            MerchantId = 10
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 3,
                            Discount = 20m,
                            MerchantId = 5
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 4,
                            Discount = 25m,
                            MerchantId = 10
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 5,
                            Discount = 30m,
                            MerchantId = 13
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 6,
                            Discount = 35m,
                            MerchantId = 6
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 7,
                            Discount = 40m,
                            MerchantId = 4
                        });
                });

            modelBuilder.Entity("ApiLibrary.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CompanyId = 2,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CompanyId = 2,
                            Name = "Jane Doe"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CompanyId = 3,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CompanyId = 3,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CompanyId = 3,
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CompanyId = 4,
                            Name = "David"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CompanyId = 5,
                            Name = "Eve"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CompanyId = 5,
                            Name = "Frank"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CompanyId = 6,
                            Name = "Grace"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CompanyId = 6,
                            Name = "Henry"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CompanyId = 7,
                            Name = "Ivy"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CompanyId = 7,
                            Name = "Jack"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CompanyId = 8,
                            Name = "Kate"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CompanyId = 8,
                            Name = "Liam"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            CompanyId = 9,
                            Name = "Mia"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CompanyId = 9,
                            Name = "Noah"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CompanyId = 10,
                            Name = "Olivia"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CompanyId = 10,
                            Name = "Peter"
                        });
                });

            modelBuilder.Entity("ApiLibrary.Models.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BenefitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId");

                    b.ToTable("Merchants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BenefitId = 1,
                            Name = "Fast Food"
                        },
                        new
                        {
                            Id = 2,
                            BenefitId = 1,
                            Name = "Restoraunt"
                        },
                        new
                        {
                            Id = 3,
                            BenefitId = 2,
                            Name = "Gym"
                        },
                        new
                        {
                            Id = 4,
                            BenefitId = 2,
                            Name = "Boxing"
                        },
                        new
                        {
                            Id = 5,
                            BenefitId = 3,
                            Name = "School"
                        },
                        new
                        {
                            Id = 6,
                            BenefitId = 3,
                            Name = "University"
                        },
                        new
                        {
                            Id = 7,
                            BenefitId = 3,
                            Name = "Englis Course"
                        },
                        new
                        {
                            Id = 8,
                            BenefitId = 4,
                            Name = "Museum"
                        },
                        new
                        {
                            Id = 9,
                            BenefitId = 4,
                            Name = "Theater"
                        },
                        new
                        {
                            Id = 10,
                            BenefitId = 5,
                            Name = "Travel Agency"
                        },
                        new
                        {
                            Id = 11,
                            BenefitId = 6,
                            Name = "Shoe store"
                        },
                        new
                        {
                            Id = 12,
                            BenefitId = 6,
                            Name = "Clothing store"
                        },
                        new
                        {
                            Id = 13,
                            BenefitId = 6,
                            Name = "Bookstore"
                        });
                });

            modelBuilder.Entity("ApiLibrary.Models.Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ApiLibrary.Models.Card", b =>
                {
                    b.HasOne("ApiLibrary.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApiLibrary.Models.CompanyBenefits", b =>
                {
                    b.HasOne("ApiLibrary.Models.Benefit", "Benefit")
                        .WithMany()
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiLibrary.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benefit");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ApiLibrary.Models.CompanyMerchantsDiscounts", b =>
                {
                    b.HasOne("ApiLibrary.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiLibrary.Models.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("ApiLibrary.Models.Employee", b =>
                {
                    b.HasOne("ApiLibrary.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiLibrary.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ApiLibrary.Models.Merchant", b =>
                {
                    b.HasOne("ApiLibrary.Models.Benefit", "Benefit")
                        .WithMany()
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benefit");
                });
#pragma warning restore 612, 618
        }
    }
}
